version: '3.9'

services:
  mysql_students:
    image: mysql:8.0.33-debian
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=alejandro
      - MYSQL_DATABASE=students_db
    ports:
      - '3306:3306'
    volumes:
      - ../mysql-students-data:/var/lib/mysql
    networks:
      - students_network

  mysql_schools:
    image: mysql:8.0.33-debian
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=alejandro
      - MYSQL_DATABASE=schools_db
    ports:
      - '3307:3306'
    volumes:
      - ../mysql-schools-data:/var/lib/mysql
    networks:
      - schools_network

  phpmyadmin_students:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_ARBITRARY='1'
      - PMA_HOST=mysql_students
      - PMA_PORT='3306'
      - PMA_USER=root
      - PMA_PASSWORD=alejandro
    ports:
      - '8888:80'
    networks:
      - students_network
    depends_on:
      - mysql_students

  phpmyadmin_schools:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_ARBITRARY='1'
      - PMA_HOST=mysql_schools
      - PMA_PORT='3306'
      - PMA_USER=root
      - PMA_PASSWORD=alejandro
    ports:
      - '8889:80'
    networks:
      - schools_network
    depends_on:
      - mysql_schools
  zipkin:
    image: openzipkin/zipkin
    ports:
      - '9411:9411'
    networks:
      - zipkin

networks:
  students_network:
  schools_network:
  zipkin:
